# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/circleci/cms
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get github.com/boltdb/bolt@v1.3.1
      - run: go get github.com/dgrijalva/jwt-go@v2.7.0+incompatible
      - run: go get github.com/elithrar/simple-scrypt@v1.3.0
      - run: go get github.com/lib/pq@v1.1.0
      - run: go get golang.org/x/crypto@v0.0.0-20190426145343-a29dc8fdc734
      - run: go get golang.org/x/net@v0.0.0-20190404232315-eb5bcb51f2a3
      - run: go get golang.org/x/oauth2@v0.0.0-20190402181905-9f3314589c9a
      - run: go get rsc.io/quote@v1.5.2
      - run: go test -v ./...