# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12
      - image: circleci/postgres:9.6-alpine
        environment: # environment variables for primary container
          POSTGRES_USER: cms
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go get -v -t -d ./...
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: 
          name: Run unit tests
          environment:
            DB_URL: "postgres://cms@localhost:5432/circle_test?sslmode=disable"
            DB_MIGRATIONS: file://
          command: go test -v ./...
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:2bcb5cc5-0aef-41f8-a00b-151fa3e3cba6@git.heroku.com/stark-oasis-56294.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master